name: frontend
replicaCount: 2

image:
  repository: frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

containerPort: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

podAnnotations: {}
podLabels: {}
imagePullSecrets: []

serviceAccount:
  create: true
  name: ""

podSecurityContext: {}
securityContext: {}
livenessProbe: {}
readinessProbe: {}
resources: {}
volumeMounts: []
volumes: []
nodeSelector: {}
affinity: {}
tolerations: []
